### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Addvilz** [bigfishtv/turret#11]
Documentation site has a really cool menu bar and side menu. Any chance of getting that as part of Turret?

**Comment by scottdejonge** [comment]
Hi @Addvilz, I'm glad you like the side menu in the docs. This is far to opinionated to be included into the Turret source, however you can see the implementation of this side menu [in the docs styles](https://github.com/bigfishtv/turret/blob/master/docs/src/styles/docs.less).

**Comment by Addvilz** [comment]
Hi, Scott! In different repo as optional extra? :)

**Comment by scottdejonge** [comment]
Sorry @Addvilz, this isn't something that will be included in Turret, feel free to use the document styles to recreate this style of menu in your projects.

**Comment by agauniyal** [comment]
+1 for sidemenu like that on frontpage 😄
