### ISSUE TITLE
No grid?

### ISSUE THREAD

**Issue by agauniyal** [bigfishtv/turret#13]
I see no support for any sort of responsive gridding system here, neither columns one nor flexbox based one, what do you guys recommend for making responsive columns?

**Comment by scottdejonge** [comment]
Previous iterations of turretcss contained a grid, the was removed in v4.0.0 to reduce the overall file size.

Now that there's support for CSS Grid and Flexbox, I've found it easier to implement a simplified grid/column system pr project to reduce required use cases.

Also feel free to import any grid system you require.

The philosophy for turretcss is to provide styles for all HTML tags `input`, `button` etc. and their states `:focus`, `:hover`, `:active`.

The issue with a coupled grid system is it become opinionated, whereas HTML and states are less opinionated. Grids need to include all possible variants for their logic, and rarely these classes are used. I've found this is best implemented per use case, or abstracted to simple rules e.g. `.column-1-2` which sets `flex: none; width: 50%;`.
