### ISSUE TITLE
turretcss v5.0.0 plan

### ISSUE THREAD

**Issue by scottdejonge** [bigfishtv/turret#21]
Writing down some idea, thoughts, and additions to turretcss for v5.0.0.

### Major Changes

- Swap [postcss-cssnext](http://cssnext.io/) dependancy for [postcss-preset-env](https://preset-env.cssdb.org/) (or alternatively create a dependancy tree from individual `postcss` packages)
- Remove `@apply` rule throughout as per discussion in #17 

### Additions

Add `xxs` and `xxl` size varients:
- `@media` queries targeting devices < 320px width (Watch etc.) and > 1920px (Smart TVs)
- `button`, `input`, `select`, `.control`, etc. elements
- `.space`, `margin`, `padding` scales potentially looking at a more standard spacing (`0.5rem`, `1rem`, `1.5rem`, `2rem`, `3rem`, `4rem`, `5rem`)

### Removal

- Remove `.big` text class with viewport text scale. It's proven to be unreliable for control and I have migrated away from using it.
- Remove `display-title` and `small-caps` text classes in favour for more scalable classes that can be chained with scale classes for more varients

### Refactoring

- Refactor `button` styles to minimise specificity for `:hover` and `:focus` states, look at removing `:not(:disabled)` for a better solution

### Ideas

- Use `HSL` for colors to utilise `calc()` for hue-rotation and greater color control from global varient presets.

**Comment by anneangersbach** [comment]
Any plans on switching to sass/scss?

**Comment by scottdejonge** [comment]
There are no plans to switch to sass/scss.

The philosophy of turretcss is to use modern CSS, using PostCSS to compile for browser support.

I am not sure what sass/scss would solve/provide. Although I am not familiar with recent sass/scss it’s been a few years.

Happy to hear any feedback!

**Comment by scottdejonge** [comment]
Current status of v5.0.0, alpha available through npm `turretcss@5.0.0-alpha1`

### Upgrades

- Upgrade `normalize.css` to `v8.0.0`
- Change PostCSS dependancy from postcss-cssnext to postcss-preset-env.
- Update dependancies to latest compatible major versions
- Commit package-lock.json
- Updated color() function to color-mod() (stage 2) CSS spec https://www.w3.org/TR/css-color-4/#funcdef-color-mod

### Breaking Changes

- Removed `@apply` rules and remove `_mixins.css` definitions along with documentation
- Removed `--gutter` and utity classes in preference for `--container-gutter` being set on the container element only
- Removed `--margin-*` and `--padding-*` custom property definitions in preference for `--space` avoiding duplicate values
- Removed font size responsive declarations for `:root` element, it's not being used, has no real benefit and is easy to update manually
- Removed `--input-*-padding` and `--select-*-padding` custom property definitions as `input` and `select` sizes already use relative padding size (`em`) and this is not required
- Removed `@apply` from `progress` and `input[type="range"]` elements
- Removed `.big` typography styles
- Removed `.small-caps` typography styles
- Removed `left-*` and `right-*` float utility classes (along with responsive breakpoint classes)

### Additions

- Added xxs, and xxl varients for all global classes (`font-size`, `line-height`, etc.) elements (`input`, `button`, etc.) and `@media` query breakpoints
- Added support for `control-reversed` modifier
- Added support for `[disabled]` attribute on `<a class="button ...">`
- Added space utility classes to add `width` and `height` to an element based on `--space-*` custom property defintions
- Added `.all-caps` as a replacement for `.small-caps` with size variants for greater flexibility
- Extended `.display-title` with size variants for greater flexibility
- Added `.group` base class size variants to be places on wrappers of `<ul>` lists with margins applied to `<li>` elements within
- Added `--spinner-width` to control the thickness of the `.spinner` element
- Added support for `.spinner-*` sizes
- Added `.box-shadow-*` sizes and utility classes
- Add `margin-negative-*` utility classes for all sizes
- Add `margin-vertical-*` utility classes for relative sizes (em) including 1, 3-4, 1-2, 1-4
- Add `min-height-*` utility classes `vh` based `min-height` settings
- Add `order-*` utility classes for 1, 2, 3 and aliases first, middle, last
- Added `.button-text` modifier class

### Fixes

- Added `.table-responsive` to margin reset
- Fixed `.button-group` not resetting `border-radius` for direct decendants
- Removed `height` from being set on `input[type="range"]` with `height: auto`
- Updated `package.json` scripts to be more descriptive and meaningful
- Fixed `.control` check indicator border color to default to checked background color
- Updated `.control:checked` indicator SVG glyph, no longer `base64` but rather `utf-8` encoding for editing and scaling purposes
- Removed `:not(:disabled)` from `input`, `.field-float-label`, `select`, and `button` styles

### Style Changes

- Tighten global `--space-*` sizes
- Increase default global `--border-radius` custom property definition to `0.125rem` (`4px`)
- Update default global `--max-width` and `--letter-spacing` custom property definitions to have generic scales
- Tightened `progress` and `input[type="range"]` heights
- Tightened `.control` size scale
- Decrease default global `--label-magin` custom property definition
- Update default global `--field-magin` and `--range-magin` custom property definition
- Updated default `<pre>` and `<code>` styles

### Documentation

- Removed `<mark>` indicator variants
- Add prettier formatter for `.md` markdown files
