### ISSUE TITLE
display and visibility class names

### ISSUE THREAD

**Issue by missmatsuko** [bigfishtv/turret#23]
### `.display-block` `.show` `.hide`
1. `.show` applies the same style as `.display-block` 
1. `.hide` applies `display: none;`, but there's no `.display-none` utility class

- I think it's kind of confusing to have 2 utility classes for the same style
- I think there should be a `.display-none` utility class for a few reasons:
  - More consistent with the rest of the display utility classes.
  - We may want to toggle between hiding/showing an element with `display: none` and a display style other than `display: block`, for example switching between `display: none;` and `display: inline-block`

### `.hidden` `.visible` `.hidden-*` `.visible-*`
1. `.hidden` applies `visibility: hidden;` and `.visible` applies `.visibility: visible;`
1. `.hidden-*` applies `display: none;` and `.visible-*` applies `display: block;`

- I think these class names are confusing. From the classnames, I would've thought `.hidden-*` (e.g. `.hidden-print`) would apply the same style as `.hidden`, which is `visibility: hidden;`.

**Comment by scottdejonge** [comment]
Hi @missmatsuko thanks for the feedback. I agree that the classnames are confusing. These are largely legacy classes that have existed since turretcss' creation.

I agree there should be a `.display-none` class. Makes sense.

Should the class names be swapped out for `.show-*` and `.hide-*`? What are your thoughts?

**Comment by missmatsuko** [comment]
Yes, I think the it would be better if `.hidden-*` and `.visible-*` classes were named `.hide-*` and `.show-*`. 

Or maybe `.display-none-*` and `.display-block-*` would more clear, but that might be too far away from what already exists.

Thanks!

**Comment by scottdejonge** [comment]
I've added two pull requests to see what I was thinking, hope this suits. #25 #24

**Comment by scottdejonge** [comment]
Merged in v5.1.0
