### ISSUE TITLE
Add browserlist to handle browser compatibility

### ISSUE THREAD

**Issue by equinusocio** [bigfishtv/turret#27]
Hi, i want to make some PR to improve this project. This is the first issue i think may be implemented. 

As the title say the project should use browserlist to define the browser compatibility and let postcss (and autoprefixer) doing their magic only when required. Using the browserlist configuration file you can easily change the target build.

postcss-preset-env [already search for it](https://github.com/csstools/postcss-preset-env#browsers) we just define the browsers query which want to support.

This tool may help:
https://browserl.ist/

here the available queries:
https://github.com/browserslist/browserslist#full-list

Right now, without any specific configuration, the default one is used by `postcss-preset-env`:

```sh
and_chr 67
and_ff 60
and_qq 1.2
and_uc 11.8
android 67
android 4.4.3-4.4.4
baidu 7.12
bb 10
bb 7
chrome 68
chrome 67
edge 17
edge 16
firefox 61
firefox 60
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 11.3-11.4
ios_saf 11.0-11.2
op_mini all
op_mob 46
op_mob 12.1
opera 55
opera 54
safari 11.1
safari 11
samsung 7.2
samsung 6.2
```

**Comment by scottdejonge** [comment]
Hey @equinusocio thanks for your suggestion, I will research best options for browserlist compatibility for autoprefixer compiling.

**Comment by equinusocio** [comment]
Worth to mention that reducing the browsers range the output bundle might be much more smaller, removing useless prefixes and conversions made by postcss-preset-env.

**Comment by scottdejonge** [comment]
Good point!

I need to focus some energy on automating linting/testing/browser configuration so that it's more predictable and controllable for different environments.

**Comment by scottdejonge** [comment]
This has been addressed with `"browserslist"` key in `package.json`
