### ISSUE TITLE
Is this section 508 or WCAG 2 compliant?

### ISSUE THREAD

**Issue by dylanz** [bigfishtv/turret#29]

**Comment by scottdejonge** [comment]
Every effort is made to ensure that turretcss is WCAG 2.1 AA compliant. The palette is created with > 4.5 contrast. However, there are always combinations of colors which would not comply. I would advise using an accessibility monitoring tool like [Pa11y](http://pa11y.org/), or Accessibility Audits within Chrome's development tools.
