### ISSUE TITLE
Font weights and names

### ISSUE THREAD

**Issue by missmatsuko** [bigfishtv/turret#32]
The [font weights and names](https://turretcss.com/base/font-weight/#css) don't match [MDN's list of common weight name mapping](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping) and they miss values for 100 and 900. 

I think it would be good to match a common standard.

**Comment by scottdejonge** [comment]
Thanks for catching this issue. It should match named values from the spec, potentially adding `.font-weight-100/900` as alternatives.

**Comment by scottdejonge** [comment]
The `font-weight-*` property definitions and values have been updated to reflect the spec in [v5.2.0](https://github.com/turretcss/turretcss/releases/tag/v5.2.0).

`font-weight-100` to `font-weight-900` utility classes have also been added.
