### ISSUE TITLE
Use of !important

### ISSUE THREAD

**Issue by missmatsuko** [bigfishtv/turret#34]
I noticed in the docs that some helper styles use `!important` to increase specificity. Is this really necessary? Could it be solved by moving down the import of those styles?

**Comment by scottdejonge** [comment]
Yeah this is a legacy thing, from older versions and is on the `no-margin/padding`, indicator classes on controls, and `.hide`/`.show` classes.

It's a weird one, as these should force their style when used. I feel it's still logical to have `!important` on these classes. I'm not certain of the implications if their specificity was to change in import order alone.

**Comment by scottdejonge** [comment]
Closing this issue but making a note of `!important` rules for future development to reduce use.
