### ISSUE TITLE
.position-[corner] classes

### ISSUE THREAD

**Issue by missmatsuko** [bigfishtv/turret#35]
From the [position docs](https://turretcss.com/utility/position/): "each position utility class is position: absolute; with top/right/bottom/left properties".

I think the `.position-[corner]` classes would be more useful if it didn't automatically add `position: absolute;`. 

Then you could use them in conjunction with the `.position-fixed` class to anchor an element to a corner of the page or `.position-relative` to anchor to a parent relative element without removing it from the flow (maybe a less useful case).

It's currently not possible to do this because the `.position-[corner]` classes come after the `position-[position]` classes, making the element `position: absolute;`.

**Comment by scottdejonge** [comment]
Agreed. This would be a breaking change and should be amended in the next major version.

Should note other `position` property values like `sticky` and what other `position-*` classes are required to leverage the most flexibility.

**Comment by scottdejonge** [comment]
`.position-[direction]` utility classes have been updated to remove `position: absolute`.

Extra classes have been added for `position-top`, `position-right`, `position-bottom`, and `position-left`.
