### ISSUE TITLE
Input "input-inverse" document example does not exist

### ISSUE THREAD

**Issue by MarkH817** [bigfishtv/turret#40]
https://github.com/turretcss/turretcss/blob/master/docs/form/input.md#html

It shows the HTML for the `.input-inverse` class, but it's neither in the Example section nor in the repository anywhere else. I think this class used to be in here, but was removed?

**Comment by scottdejonge** [comment]
Hey @MarkH817 good catch!

This was a style that existed in previous versions and has since been removed.

I have updated the docs to reflect this.

Thank you for letting me know.
