### ISSUE TITLE
Select element cannot have a label

### ISSUE THREAD

**Issue by cramarokoto** [bigfishtv/turret#46]
```
<p class="field">
  <label class="select" for="select">
    The label
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
  </label>
</p>
```

**Current behavior :**
The select element has no label text in examples.
Adding a label text leads to broken style for the select dropdown arrow and the label is not formatted like the other labels.

![image](https://user-images.githubusercontent.com/51867190/83365281-445c7f80-a3a7-11ea-9979-574dc19b2e44.png)

**Expected behavior :**
The select element has a label in examples.
The select can be used with or without label.

**Comment by cramarokoto** [comment]
Hi ! I'm a great fan of your work, I hope my issue is well formatted and comprehensible. Thank you for the good work !

**Comment by scottdejonge** [comment]
Hi @cramarokoto, can you do the following?

```html
<p class="field">
  <label for="select">
    The label
  </label>
  <label class="select" for="select">
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
  </label>
</p>
```

Where the first `<label>` is using the label styles and has a `for="select"` attribute to focus the `<select>` when interacted with.

The second `<label class="select">` is for cross-browser styling of the `<select>`.

**Comment by cramarokoto** [comment]
That works visually and is HTML5 compliant but the label without descriptive text is missing semantics : it's only there for styling and brings no labeling information.
I also don't know how screen readers react to this situation.

**Comment by cramarokoto** [comment]
For example, [AChecker](https://achecker.ca/checker/index.php) (a web accessibility checker) considers that to be an issue as seen [here](https://achecker.ca/checker/suggestion.php?id=188).

**Comment by adamroyle** [comment]
Hi @cramarokoto, thanks for your feedback. If you feel it's necessary, you can change the wrapping `<label class="select">` to a `<div class="select">` tag.

```diff
<p class="field">
  <label for="select">
    The label
  </label>
- <label class="select" for="select">
+ <div class="select">
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
- </label>
+ </div>
</p>
```

**Comment by cramarokoto** [comment]
Thank you for your quick answers.

Unfortunately, `p` cannot contain block level elements such as `div` and that makes organising the form complicated. I will switch to `fieldset` but that stills means I change the semantic of the form for the visual rendering.

```
<fieldset class="field">
  <label for="select">
    The label
  </label>
  <div class="select">
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
  </div>
</fieldset>
```

**Comment by scottdejonge** [comment]
Perhaps a `<span>` would be your best bet here:

```diff
<p class="field">
  <label for="select">
    The label
  </label>
- <label class="select" for="select">
+ <span class="select">
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
- </label>
+ </span>
</p>
```

I'd argue that a `<fieldset>` would be best suited to a group of inputs and may have side effects which may disorientate users of screen readers who are not familiar with your suggest pattern.

A `<fieldset>` will also require a nested `<legend>` to provide it context within the accessibility tree.

Alternatively using the native `<select>`, without the HTML workaround for styling in turretcss, might also be a better option: https://css-tricks.com/styling-a-select-like-its-2019/

Depending on your browser support requirements, and appetite for testing across browsers and devices, this would give you more granular control with how you present your HTML.

**Comment by cramarokoto** [comment]
I agree with you, the `fieldset` is also a bad idea on second thought. The span seems to match that usage. Thanks !

I'm trying to stick to what's already available in this library since it's really flexible and clean (semantics and accessibility are not polluted by an overuse of wrappers such as `div`).

**Comment by scottdejonge** [comment]
I believe that the information you are receiving from ACChecker may be a false positive test result if you have the following:

```html
<p class="field">
  <label for="select">
    The label
  </label>
  <label class="select" for="select">
    <select id="select">
      <option>Select Field</option>
      <option value="1">Option 01</option>
      <option value="2">Option 02</option>
    </select>
  </label>
</p>
```

This is because:

1. `<select>` is labelled by an associated label above
2. `<label class="select" for="select">` wrapping the `<select>` is included for the pointer events to be provided to the child. When a keyboard user focuses the `<select>` they provided with the text from the associated `<label>` above.

I believe that the tool is evaluating `<label class="select" for="select">...</label>` as a failure because it doesn't contain a textnode, however, this isn't a concern as the `<select>` is already laballed.

WCAG 3.3.2: https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html

**Comment by scottdejonge** [comment]
> I agree with you, the `fieldset` is also a bad idea on second thought. The span seems to match that usage. Thanks !
> 
> I'm trying to stick to what's already available in this library since it's really flexible and clean (semantics and accessibility are not polluted by an overuse of wrappers such as `div`).

Good call! I hope that the usage of `<span>` resolves this issue.
