### ISSUE TITLE
Feature request: use turretcss as a no-side-effect utility library?

### ISSUE THREAD

**Issue by leaumar** [bigfishtv/turret#49]
I'd like to use turretcss as a utility library, like how basscss works (which lacks e.g. the cursor utils). Turretcss applies a global default style to elements though, and I found no way to disable this in the documentation.

One could import the files in `turret/utility` one by one, but that's not a great way to work. Would it be possible to have e.g. a `disable-turret-defaults` class that could be added on the `<body>` to disable turret's default styling, or some other simple and proper way to achieve that? Perhaps a bundled/distributed separate import target to get all the utilities at once without the default styles?

I could have a go at PRing this if you say you're not against the idea, but I don't know if e.g. you consider this out of scope and don't want it.

**Comment by scottdejonge** [comment]
@leaumar while I understand the benefits of doing so, I think that would go against the philosophy of turretcss which primarily themes default HTML elements to enforce the use of semantic HTML.

There are shortcomings of turretcss's approach here, it can be difficult to use HTML elements in a way different to how turretcss has styled it (I'm looking at your `<button>`!).

I would argue that even with a disabling class on `<body>` there will still be shortcomings in the utility classes, i.e. no stateful utility classes (`:hover`, `:focus`, `:active` etc.).

I would suggest you look into [Tailwind](https://github.com/tailwindlabs/tailwindcss) or [Hucssley](https://github.com/stowball/hucssley) to achieve the utility-first approach.

**Comment by leaumar** [comment]
Yeah, that's understandable. Thanks for the huccsley tip, it's a tad verbose but in the right direction. Been googling for days trying to find something like basscss (but bigger, e.g. cursor classes, and still a single dep) that feels right to me, have really only found quantum-css acceptable so far.
