### ISSUE TITLE
Packaging: configuration

### ISSUE THREAD

**Issue by ghost** [bigfishtv/turret#5]
Hi!

As the configuration is writen in each .less component file, it cannot be override without modifying the package source code.

What do you think about putting the variables in another file?

**Comment by ifunk** [comment]
Less variables can be changed _after_ they are used, so just import a custom definitions file after you import turret.less

``` less
// import turret
@import 'path_to_turret/turret/turret.less';

// import some custom variables
@import 'my-custom-variables.less';
```
