### ISSUE TITLE
first-child and grids/flexboxes

### ISSUE THREAD

**Issue by yurkobb** [bigfishtv/turret#59]
The styles that wipe margin-top on :first-child elements make it awkward to work in situations where the items are placed in a grid or flexbox, i.e., in a horizontal layout, as the first and subsequent items' margins are not equal:

![Two input fields on a page, Name and Phone, where the first one is not aligned vertically with the second one.](https://user-images.githubusercontent.com/479389/124478577-fede6300-ddad-11eb-89d8-b9c72b2dc6b6.png)

A [codepen demo](https://codepen.io/undltd/pen/eYWJdaN).

I'm not sure what would be the most clean approach to work around this; perhaps an additional class could be provided that when applied to a parent element would revert the effect of the first-child stiles on the children... Not sure.

**Comment by adamroyle** [comment]
@yurkobb A few options

You can wrap each `.field` in another element. This will mean no margins will be added.

```html
<div><p class="field">...</p></div>
``` 

You can add `.no-margin` to the field specifically.

```html
<p class="field no-margin">...</p>
```

Or specify in your css if you're creating custom classes anyway. You may wish to do this if you're using media queries to conditionally add/change grid template.

```css
.myform > * {
  margin: 0;
}
```

**Comment by yurkobb** [comment]
Thanks, the last option fits my use case best.
