### ISSUE TITLE
Bower repository

### ISSUE THREAD

**Issue by eduardhojbota** [bigfishtv/turret#8]
Could you please publish your framework on bower as well?

**Comment by scottdejonge** [comment]
Sorry for the delay. I've added the bower.json files to the repo and registered the project with bower.

**Comment by gokaygurcan** [comment]
I was here to ask the same question, thanks for bower entry. Could you please also update docs and readme? I assume, only a small portion of people checks closed issues tab on GitHub :)
Thanks in advance, and thanks for the good job.

**Comment by scottdejonge** [comment]
Sorry for that. I have added into documentation and README with v3.1.3 release

**Comment by gokaygurcan** [comment]
:+1: thanks a lot!
