### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by gokaygurcan** [bigfishtv/turret#9]
Are you planning to add Sass support soon? If not, can we do that?

**Comment by scottdejonge** [comment]
Hey @gokaygurcan, There isn't any plan for Sass support at the moment, purely due to our internal workflow. If you were looking to, feel free to fork Turret and add Sass support.

**Comment by gokaygurcan** [comment]
Good to know, thanks! Then i'm starting to work on Sass port ;)

**Comment by scottdejonge** [comment]
I look forward to it!
